language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.9-thr"
  - "5.8.9"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.24.2-thr"
  - "5.26"
matrix:
  allow_failures:
    # Test::More issues?
    - perl: "5.6.2"
  include:
    - perl: "5.24"
      env: COVERAGE=1
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/tobyink/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -l -v "t"
after_success:
  - coverage-report
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change

